name: Publish Package to GitHub NPM Registry

on:
  release:
    types: published

jobs:
  npm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install the npm dependencies
        run: npm install

      - name: Publish to the npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
